import React from "react";
import AdminLayout from "../../components/layout/AdminLayout";
import Head from "next/head";
const AdminHome = () => {
  return (
    <>
      <Head>
        <title>Admin Panel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{background: 'orange'}}>AdminHome</div>
    </>
  );
};

AdminHome.layout = AdminLayout;

export default AdminHome;
